language: node_js
sudo: false
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
node_js:
  - 12
os:
  - osx
script:
  - npm run lint
  - npm test
# jobs:
#   include:
#     - stage: release
#       if: branch = master
#       node_js: 12
#       script:
#         - npm run release
notifications:
  email:
    on_success: never
    on_failure: always
