#!/bin/bash

# build the app
npm run compile
electron-packager ./dist --out ./output --overwrite true --icon ./assets/icons/mac/wechat-ai.icns


# create dmg
PACKAGE_VERSION=$(node -p "require('./package.json').version")
FILE_NAME="output/WeChat_AI-darwin-x64-v${PACKAGE_VERSION}.dmg"
rm -f "${FILE_NAME}"
appdmg scripts/build-mac.json "${FILE_NAME}"
