#!/bin/bash

export NODE_ENV=test

# --watch option
if [ -n "$npm_config_platform" ]; then PLATFORM=" --platform"; else WATCH=""; fi

# --coverage option
if [ -n "$npm_config_coverage" ]; then COVERAGE=" --coverage"; else COVERAGE=""; fi

electron-packager . \"WeChat AI\" --out ./.output --packageManager yarn --overwrite true
